package com.proyecto.empleadosapi.controller;

import com.proyecto.empleadosapi.model.Employee;
import com.proyecto.empleadosapi.repository.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.proyecto.empleadosapi.repository.UserRepository;
import com.proyecto.empleadosapi.model.User;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/employee") // This means URLs start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository employeeRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser(@RequestParam String firstName, @RequestParam String lastName) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Employee employee = new Employee(firstName, lastName);
        employeeRepository.save(employee);
        return "Saved";
    }

    @GetMapping("/all")
    public @ResponseBody Iterable<Employee> getAllEmployers() {
        // This returns a JSON or XML with the employee
        return employeeRepository.findAll();
    }
}